### ISSUE TITLE
line feeds

### ISSUE THREAD

**Issue by xwitty** [XLixl4snSU/yourls-telegram-notifier#1]
Hi, thanks for this plugin!
any way, I can add line-feeds to the message?
thanks

**Comment by XLixl4snSU** [comment]
Hi, I'm glad you find my plugin useful.

I've made a minor change that should enable this functionality for you and released a new version.

Just do a new line in the text field and your notifications should respect these.

**Comment by xwitty** [comment]
Hi, wow - did not expect this quick reaction :-) thanks!!
* tested with `The\n%url\nwas shorted` -> I see `\n` as text in the message (but no LF).
* I tried to deactivate/activate the plugin after saving new plugin.php -> deactivation does not respond (empty result page)

**Comment by XLixl4snSU** [comment]
No problem, I had some free time 😄 

Did you install the new version? Replace all files of the plugin, not just the plugin.php. (The relevant change is in includes/admin-page.php)

It should look something like this:
![image](https://github.com/XLixl4snSU/yourls-telegram-notifier/assets/111450124/311f7dfa-b483-4690-9577-b31f6bba49a2)

**Comment by xwitty** [comment]
Okay, that was easy ;)
But I thought, I need to deactivate before re-installing (this is why I mentioned the „deactivation“-failure). Works great! Thanks!!
